import chalk from "chalk"
import { confirm,isCancel,text } from "@clack/prompts"
import { ToolLoopAgent,stepCountIs,tool } from "ai"
import {z} from "zod"
import { getAgentModel } from "../../ai"
import {ActionTracker} from "../agents/action-tracker"
import {ToolExecutor} from "../agents/tool-executor"
import {defaultAgentConfig} from "../agents/types"
